import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ShieldCheck, MessageSquare, Clock, ArrowRight, Activity, Database, Brain, Shield } from 'lucide-react'

const cards = [
  {
    to: '/safety-check',
    icon: ShieldCheck,
    color: 'var(--accent)',
    bg: 'var(--accent-subtle)',
    title: 'Safety Check',
    desc: 'Analyze drug interactions & contraindications against FHIR patient data with real FDA adverse event reports.',
  },
  {
    to: '/chat',
    icon: MessageSquare,
    color: 'var(--success)',
    bg: 'var(--success-bg)',
    title: 'Ask AI',
    desc: 'Chat with HealthMind about medications, drug risks, clinical guidelines, and safety protocols.',
  },
  {
    to: '/history',
    icon: Clock,
    color: 'var(--warning)',
    bg: 'var(--warning-bg)',
    title: 'History',
    desc: 'Review past safety check results, recommendations, and audit trail.',
  },
]

const stats = [
  { icon: Activity, value: 'Real-time', label: 'openFDA AERS data' },
  { icon: Database, value: 'FHIR R4', label: 'Patient records' },
  { icon: Brain, value: '8 Rules', label: 'Safety engine' },
  { icon: Shield, value: '100%', label: 'HITL coverage' },
]

const container = {
  hidden: {},
  show: { transition: { staggerChildren: 0.08 } },
}

const item = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.25, 0.46, 0.45, 0.94] } },
}

export default function Home() {
  return (
    <div className="page page-wide">
      {/* Hero */}
      <motion.div
        initial={{ opacity: 0, y: -15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: 'easeOut' }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 8 }}>
          <div style={{
            width: 48, height: 48, borderRadius: 14,
            background: 'var(--accent-subtle)', display: 'flex',
            alignItems: 'center', justifyContent: 'center', fontSize: 24,
          }}>
            🧠
          </div>
          <div>
            <h1 className="page-title">HealthMind</h1>
            <p className="page-subtitle">AI-powered prescription safety agent</p>
          </div>
        </div>
      </motion.div>

      {/* Stats Row */}
      <motion.div
        className="stats-row"
        variants={container}
        initial="hidden"
        animate="show"
      >
        {stats.map(({ icon: Icon, value, label }, i) => (
          <motion.div key={i} variants={item} className="card stat-card">
            <Icon size={20} color="var(--accent)" style={{ margin: '0 auto 8px' }} />
            <div className="stat-value">{value}</div>
            <div className="stat-label">{label}</div>
          </motion.div>
        ))}
      </motion.div>

      {/* Action Cards */}
      <motion.div
        className="home-grid"
        variants={container}
        initial="hidden"
        animate="show"
        style={{ marginTop: 28 }}
      >
        {cards.map(({ to, icon: Icon, color, bg, title, desc }) => (
          <motion.div key={to} variants={item}>
            <Link to={to} className="home-card">
              <div className="card card-hover card-interactive">
                <div className="home-card-icon" style={{ background: bg }}>
                  <Icon size={24} color={color} />
                </div>
                <div>
                  <div className="home-card-title">{title}</div>
                  <div className="home-card-desc">{desc}</div>
                </div>
                <div className="home-card-arrow">
                  <ArrowRight size={18} />
                </div>
              </div>
            </Link>
          </motion.div>
        ))}
      </motion.div>

      {/* HITL Banner */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5, duration: 0.5 }}
        style={{
          marginTop: 32,
          padding: 22,
          background: 'var(--accent-subtle)',
          border: '1px solid var(--accent-glow)',
          borderRadius: 'var(--radius-lg)',
          display: 'flex',
          gap: 14,
          alignItems: 'flex-start',
        }}
      >
        <Shield size={20} color="var(--accent)" style={{ flexShrink: 0, marginTop: 2 }} />
        <div>
          <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--accent)', letterSpacing: 0.8, marginBottom: 4 }}>
            HUMAN-IN-THE-LOOP SAFETY
          </div>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            Every recommendation generated by HealthMind is marked <code style={{ color: 'var(--accent)', background: 'var(--bg-card)', padding: '2px 6px', borderRadius: 4, fontSize: 12 }}>hitl_required: true</code>. 
            AI-generated safety assessments supplement — never replace — clinical judgment. The physician always makes the final prescribing decision.
          </div>
        </div>
      </motion.div>
    </div>
  )
}
